baseURL = "https://winsider.hu"
languageCode = "hu-hu"
title = "WINSIDER"
theme = "github.com/theNewDynamic/gohugo-theme-ananke"

[module]
  [[module.imports]]
  path = "github.com/theNewDynamic/gohugo-theme-ananke"

[params]
favicon = ""
site_logo = ""
description = "Egy újabb Windows blog"
facebook = "https://www.facebook.com/winsiderhu"
twitter = ""
instagram = ""
youtube = "https://www.youtube.com/channel/UCQyCizOBCYx5QSCe8tH9fRQ"
github = ""
gitlab = ""
linkedin = ""
mastodon = ""
slack = ""
stackoverflow = ""
rss = ""
background_color_class = "bg-dark-blue"
recent_posts_number = 2.0